server {
    listen 5373;

    root /usr/share/nginx/html;
    index index.html;

    # React Router — renvoyer index.html pour toutes les routes
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy /api vers le backend
    location /api {
        proxy_pass http://server:4800/api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
